Single player
MeiNic/MenschAergereDichNicht pull request #54
Opened 2023-08-03 14:17 UTC by TastingComb

1. made a Single player mode possible (changed minimum number of JSpinner to 1
2. implemented a JLabel to show when you don't get a six to move out of base (with jButton to move on to next player)
3. implemented an message for the user that shows the bot movements, so user can see what's happening in the BackEnd

2023-08-04 10:10 UTC, guemax commented on BackEnd.java
> -	    // Only figures able to beat another figure should be
I added a hard line break in this comment to keep the line width under 72 characters.

Sticking with that number might seem odd (it is from a time where programmers used punch cards), but it really simplifies reading code when I have two windows side by side as the code fits perfectly on that limited amount of space.

2023-08-04 10:11 UTC, guemax commented on BackEnd.java
> -	    // moved now.
I added a hard line break in this comment to keep the line width under 72 characters.

Sticking with that number might seem odd (it is from a time where programmers used punch cards), but it really simplifies reading code when I have two windows side by side as the code fits perfectly on that limited amount of space.

2023-08-06 20:32 UTC, MeiNic requested changes
There is a lot to do in the `backEnd.java` file:
1. Please remove/add **ALL** unnecessary indentations, bescause this code is nearly unreadable (some of the changes are only unnecesary added indentations e.g. line 321 till 324)
2. Remove **ALL** empty lines unnecessary added
3. Remove the unused variable: `movedFieldsNew` (line 170)
4. Remove variable `movedFields` (values is always the same as the variable `randomNumber`)
5. Add the linebreak between line 120 and 121 (see the comment from [guemax](https://github.com/guemax))

There is also following bug:
After one or more bots made their move, the result for the normal user isn't displayed anymore.
Could you fix this as well?

2023-08-11 08:48 UTC, MeiNic commented
This PR is closed, until the structure-updates from @guemax are on the master-branch.
Then the need changes for the `SinglePlayer`-Mode can may be implemented in another branch, because otherwise there into big difference and it gets complicated to merge this PR.

2023-08-11 08:48 UTC, closed without merging